package br.com.cofermeta.toolbox.model.dataclasses

data class ListagemDeProdutos (
    var CODPROD: String = "",
    var CODIGO_LEGADO: String = "",
    var PRODUTO: String = "",
    var UNIDADE_MEDIDA: String = "",
    var LOC_PRINCIPAL: String = "",
    var PRECO: String = "",
    var CODIGO_FORNECEDOR: String = "",
    var REFERENCIA_FORNECEDOR: String = "",
    var CODIGO_DE_BARRAS: String = "",
    var MARCA: String = "",
    var REF_FORNECEDOR: String = "",
    var CATEGORIA: String = "",
    var PESO: String = "",
    var ORIGEM: String = "",
    var NCM: String = "",
    var ORIGEM_PRODUTO: String = "",
    var COD_LOCAL: String = "",
    var EST_RESERVADO: String = "",
    var SITUACAO_ESTOQUE: String = "",
    var ESTOQUE: String = "",
    var ESTOQUE_DISPONIVEL: String = "",
    var ESTOQUE_MINIMO: String = "",
    var ESTOQUE_MAXIMO: String = "",
    var ATIVO: String = "",
    var CUSTO_GERENCIAL: String = "",
    var CUSREP: String = "",
    var CUSVAR: String = "",
    var COD_FORN: String = "",
    var FORNECEDOR: String = "",
    var COD_LINHA: String = "",
    var LINHA: String = "",
    var CODPRODECOM: String = "",
    var ENDIMAGEM: String = "",
)
